//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDTableOperations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRUDTableOperations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TDW_TABLE_MANAGER.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namib Mills.
        /// </summary>
        public static string DataGrid1PageTitle {
            get {
                return ResourceManager.GetString("DataGrid1PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string ShellGoBackButton {
            get {
                return ResourceManager.GetString("ShellGoBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string ShellMenuFileHeader {
            get {
                return ResourceManager.GetString("ShellMenuFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ShellMenuItemFileExitHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemFileExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namib Mills Table.
        /// </summary>
        public static string ShellMenuItemViewsDataGrid1PageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsDataGrid1PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Table.
        /// </summary>
        public static string ShellMenuItemViewsDataGridPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsDataGridPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string ShellMenuItemViewsMainPageHeader {
            get {
                return ResourceManager.GetString("ShellMenuItemViewsMainPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Views.
        /// </summary>
        public static string ShellMenuViewsHeader {
            get {
                return ResourceManager.GetString("ShellMenuViewsHeader", resourceCulture);
            }
        }
    }
}
